name: sign_flow
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.7
  syncfusion_flutter_pdfviewer: ^31.2.15
  syncfusion_flutter_signaturepad: ^31.2.15
  syncfusion_flutter_pdf: ^31.2.15
  path_provider: ^2.1.2
  permission_handler: ^12.0.1
  cupertino_icons: ^1.0.8
  share_plus: ^12.0.1
  google_fonts: ^6.3.2
  shared_preferences: ^2.3.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/certificate.pfx

# --- LOGO AYARLARI ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21